// modernUtilities.js
// Modern UI styles for RiderPage - separated from component

import colors from "./colors";

export const modernUtilities = {
    container: {
        flex: 1,
        backgroundColor: '#000000',
    },
    headerContainer: {
        backgroundColor: '#151515',
        paddingBottom: 5,
        paddingHorizontal: 20,
        borderBottomLeftRadius: 20,
        borderBottomRightRadius: 20,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 8,
        elevation: 5,
    },
    userSection: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        marginBottom: 5,
    },
    userInfo: {
        flex: 1,
        flexDirection: 'row',
        alignItems: 'center',
    },
    avatar: {
        width: 45,
        height: 45,
        borderRadius: 25,
        backgroundColor: 'rgba(255,255,255,0.2)',
        alignItems: 'center',
        justifyContent: 'center',
        marginRight: 12,
    },
    userDetails: {
        flex: 1,
    },
    welcomeText: {
        color: '#fff',
        fontSize: 14,
        opacity: 0.9,
    },
    usernameText: {
        color: '#fff',
        fontSize: 18,
        fontWeight: 'bold',
    },
    riderTypeBadge: {
        flexDirection: 'row',
        alignItems: 'center',
        marginTop: 3,
    },
    riderTypeText: {
        color: '#fff',
        fontSize: 12,
        opacity: 0.9,
    },
    searchContainer: {
        height: 50,
        width: 120,
        borderWidth: 1,
        borderRadius: 25,
    },
    quickActions: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        gap: 12,
    },
    createButton: {
        backgroundColor: '#fff',
        flex: 1,
        paddingVertical: 12,
        paddingHorizontal: 20,
        borderRadius: 25,
        alignItems: 'center',
        justifyContent: 'center',
        flexDirection: 'row',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 3,
    },
    createButtonText: {
        color: '#8c2323',
        fontSize: 15,
        fontWeight: '600',
        marginLeft: 6,
    },
    searchButton: {
        backgroundColor: 'rgba(255,255,255,0.15)',
        paddingHorizontal: 12,
        paddingVertical: 12,
        borderRadius: 20,
        alignItems: 'center',
        justifyContent: 'center',
    },
    contentContainer: {
        flex: 1,
        backgroundColor: '#000000',
        paddingTop: 10,
        paddingBottom: 10,
    },

    activeRideCard: {
        backgroundColor: '#151515',
        borderRadius: 15,
        padding: 16,
        marginBottom: 12,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 8,
        elevation: 3,
        borderLeftWidth: 4,
    },
    activeRideHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        marginBottom: 8,
    },
    activeStatus: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#e8f5e8',
        paddingHorizontal: 8,
        paddingVertical: 4,
        borderRadius: 12,
    },
    activeStatusText: {
        color: '#27ae60',
        fontSize: 11,
        fontWeight: '600',
        marginLeft: 4,
    },
    activeRideLocation: {
        fontSize: 16,
        fontWeight: '600',
        color: '#ffffff',
        marginBottom: 4,
    },
    activeRideName: {
        fontSize: 14,
        color: '#ffffff',
        marginBottom: 4,
    },
    activeRideId: {
        fontSize: 12,
        color: '#95a5a6',
    },
    feedSection: {
        flex: 1,
    },

    bottomContainer: {
        backgroundColor: '#151515',
        paddingVertical: 5,
        paddingHorizontal: 5,
        borderTopWidth: 4,
        borderTopLeftRadius: 20,
        borderTopRightRadius: 20,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: -2 },
        shadowOpacity: 0.1,
        shadowRadius: 8,
        elevation: 5,
    },
    myRidesButton: {
        backgroundColor: '#8c2323',
        paddingVertical: 12,
        paddingHorizontal: 24,
        borderRadius: 25,
        alignItems: 'center',
        justifyContent: 'center',
        alignSelf: 'center',
    },
    myRidesButtonText: {
        color: '#fff',
        fontSize: 15,
        fontWeight: '600',
    },
    emptyState: {
        alignItems: 'center',
        justifyContent: 'center',
        paddingVertical: 30,
    },
    emptyStateText: {
        fontSize: 14,
        color: '#7f8c8d',
        marginTop: 8,
    },
    loadingContainer: {
        alignItems: 'center',
        justifyContent: 'center',
        paddingVertical: 20,
    },
    errorText: {
        fontSize: 14,
        color: '#e74c3c',
        textAlign: 'center',
        paddingVertical: 20,
    },
};