import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
    modalOverlay: {
        flex: 1,
        backgroundColor: 'rgba(0, 0, 0, 0.85)',
        justifyContent: 'center',
        alignItems: 'center',
    },
    modalContainer: {
        backgroundColor: '#0a0a0a',
        borderRadius: 24,
        width: '90%',
        maxHeight: '85%',
        borderWidth: 1,
        borderColor: '#222',
    },

    modalTitle: {
        color: '#fff',
        fontSize: 22,
        fontWeight: '700',
        marginBottom: 4,
    },
    modalSubtitle: {
        color: '#666',
        fontSize: 13,
        fontWeight: '500',
    },
    closeButton: {
        alignItems: 'center',
        justifyContent: 'center',
        marginLeft: 'auto',
    },

    // QR Code Section
    qrCodeSection: {
        backgroundColor: '#111',
        borderRadius: 16,
        padding: 20,
        marginHorizontal: 20,
        marginTop: 16,
        marginBottom: 8,
        borderWidth: 1,
        borderColor: '#222',
        alignItems: 'center',
    },
    qrCodeTitle: {
        color: '#fff',
        fontSize: 16,
        fontWeight: '600',
        marginBottom: 12,
    },
    qrCodeContainer: {
        backgroundColor: '#fff',
        borderRadius: 12,
        padding: 16,
        alignItems: 'center',
        justifyContent: 'center',
    },
    qrCodeImage: {
        width: 200,
        height: 200,
        borderRadius: 8,
    },
    qrCodePlaceholder: {
        width: 200,
        height: 200,
        backgroundColor: '#f1f5f9',
        borderRadius: 8,
        alignItems: 'center',
        justifyContent: 'center',
    },
    qrCodePlaceholderText: {
        color: '#64748b',
        fontSize: 12,
        fontWeight: '500',
        marginTop: 8,
    },
    qrCodeActions: {
        flexDirection: 'row',
        marginTop: 16,
        gap: 12,
    },
    qrActionButton: {
        flex: 1,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: '#8c2323',
        paddingVertical: 10,
        paddingHorizontal: 16,
        borderRadius: 10,
        gap: 8,
    },
    qrActionButtonSecondary: {
        backgroundColor: '#222',
    },
    qrActionButtonText: {
        color: '#fff',
        fontSize: 13,
        fontWeight: '600',
    },

    tabContainer: {
        flexDirection: 'row',
        paddingHorizontal: 20,
        paddingTop: 16,
        gap: 12,
    },
    tab: {
        flex: 1,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        paddingVertical: 12,
        paddingHorizontal: 16,
        borderRadius: 12,
        backgroundColor: '#111',
        borderWidth: 1,
        borderColor: '#222',
    },
    tabActive: {
        backgroundColor: 'rgba(140, 35, 35, 0.1)',
        borderColor: '#8c2323',
    },
    tabText: {
        color: '#666',
        fontSize: 14,
        fontWeight: '600',
    },
    tabTextActive: {
        color: '#8c2323',
    },
    tabBadge: {
        backgroundColor: '#333',
        borderRadius: 10,
        paddingHorizontal: 8,
        paddingVertical: 2,
        marginLeft: 8,
    },
    tabBadgeText: {
        color: '#fff',
        fontSize: 11,
        fontWeight: '700',
    },
    contentContainer: {
        flex: 1,
        paddingHorizontal: 20,
        paddingTop: 20,
    },
    participantsContainer: {
        flex: 1,
    },
    participantsList: {
        paddingBottom: 8,
    },
    participantCard: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#111',
        borderRadius: 12,
        padding: 16,
        borderWidth: 1,
        borderColor: '#222',
        marginBottom: 12,
    },
    participantNumber: {
        width: 32,
        height: 32,
        borderRadius: 16,
        backgroundColor: '#8c2323',
        alignItems: 'center',
        justifyContent: 'center',
        marginRight: 12,
    },
    participantNumberText: {
        color: '#fff',
        fontSize: 14,
        fontWeight: '700',
    },
    participantInfo: {
        flex: 1,
        flexDirection: 'row',
        alignItems: 'center',
        marginRight: 8,
    },
    participantName: {
        color: '#fff',
        fontSize: 15,
        fontWeight: '600',
    },
    ownerBadge: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: 'rgba(251, 191, 36, 0.1)',
        borderRadius: 8,
        paddingHorizontal: 8,
        paddingVertical: 4,
        marginLeft: 8,
    },
    ownerBadgeText: {
        color: '#fbbf24',
        fontSize: 10,
        fontWeight: '700',
        textTransform: 'uppercase',
    },
    requestCard: {
        backgroundColor: '#111',
        borderRadius: 12,
        padding: 16,
        marginBottom: 8,
        borderWidth: 1,
        borderColor: '#222',
    },
    requestCardContent: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
    },
    requestUserInfo: {
        flex: 1,
        flexDirection: 'row',
        alignItems: 'center',
        gap: 12,
    },
    avatarPlaceholder: {
        width: 40,
        height: 40,
        borderRadius: 20,
        backgroundColor: '#222',
        alignItems: 'center',
        justifyContent: 'center',
    },
    requestUsername: {
        color: '#fff',
        fontSize: 15,
        fontWeight: '600',
        marginBottom: 2,
    },
    requestDate: {
        color: '#666',
        fontSize: 12,
        fontWeight: '500',
    },
    requestStatus: {
        fontSize: 11,
        fontWeight: '600',
        textTransform: 'uppercase',
        marginTop: 4,
    },
    statusPending: {
        color: '#f59e0b',
    },
    statusApproved: {
        color: '#10b981',
    },
    statusRejected: {
        color: '#ef4444',
    },
    requestActions: {
        flexDirection: 'row',
        gap: 8,
    },
    actionButton: {
        width: 40,
        height: 40,
        borderRadius: 20,
        alignItems: 'center',
        justifyContent: 'center',
    },
    approveButton: {
        backgroundColor: '#10b981',
    },
    rejectButton: {
        backgroundColor: '#ef4444',
    },
    acceptButton: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#8c2323',
        paddingVertical: 8,
        paddingHorizontal: 16,
        borderRadius: 20,
        gap: 6,
    },
    acceptButtonText: {
        color: '#fff',
        fontSize: 13,
        fontWeight: '600',
    },
    loadingContainer: {
        flex: 1,
        alignItems: 'center',
        justifyContent: 'center',
        paddingVertical: 60,
    },
    loadingText: {
        color: '#666',
        fontSize: 14,
        fontWeight: '500',
        marginTop: 12,
    },
    errorContainer: {
        flex: 1,
        alignItems: 'center',
        justifyContent: 'center',
        paddingVertical: 60,
    },
    errorText: {
        color: '#8c2323',
        fontSize: 14,
        fontWeight: '500',
        textAlign: 'center',
        marginTop: 12,
    },
    emptyState: {
        alignItems: 'center',
        justifyContent: 'center',
        paddingVertical: 60,
    },
    emptyStateText: {
        color: '#fff',
        fontSize: 16,
        fontWeight: '600',
        marginTop: 16,
        marginBottom: 8,
    },
    emptyStateSubtext: {
        color: '#666',
        fontSize: 13,
        fontWeight: '500',
        textAlign: 'center',
    },
});
